config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  get 'pages/contact'
  get 'pages/resources'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'categories/index'
  get 'categories/edit'
  get 'categories/new'
  get 'categories/show'
  get 'home/index'
  root 'home#index'
  resources :posts
  resources :categories

  get '/about', :to => 'pages#about'
  get '/contact', :to => 'pages#contact'
  get '/resources', :to => 'pages#resources'
  

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :posts
	
end

app/models/gategory.rb
class Gategory < ApplicationRecord

	def category_params
		params.require(:gategory).permit(:name)
	end
	has_many :posts
end

app/models/post.rb
class Post < ApplicationRecord

	def post_params
		params.require(:post).permit(:title, :body, :category_id, :author_id)
	end
	# attr_accessible :name, :body, :category_id, :author_id
	belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])
    @posts = @category.posts
  end

  # GET /categories/new
  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end

  def resources
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		# @search = Post.search(params[:search])
		@posts = Post.all
		@categories = Category.all
		# @first_body = "This is the first post body"
		# @second_body = "This is the Second post body"

	end


	def show

		@post = Post.find(params[:id])

	end


	def new

		@post = Post.new
		@category = Category.all
	end


	def create

		@post = Post.new(post_params)
		if @post.save
			redirect_to posts_path, :notice => "Your post has been saved!"

		else
			render "new"
		end

	end


	def edit

		@post = Post.find(params[:id])

	end


	def update
		@post = Post.find(params[:id])

		if @post.update_attributes(post_params)
			redirect_to post_path
		else
			render "edit"
		end
	end


	def destroy
		@post = Post.find(params[:id])
		@post.destroy
		redirect_to posts_path

	end

	def post_params
		params.require(:post).permit(:title, :body, :category_id, :author_id)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Categories</h1>


  <% @categories.each do |category| %>
    
    <li><%= link_to category.name, category %></li>
        
      
  <% end %>
<br>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<h1><strong><%= @category.name %> Posts</strong></h1>

<% if @posts.each do |post| %>
	<div class="jumbotron" style="margin-bottom: 10px;">
			<h3><%= link_to post.title, post%></h3>
			<p class="lead"><%= post.body%></p>
		</div>

<% end.empty? %>
	<p>Sorry, There is no post here!</p>
<% end %>

<hr>
<%= link_to 'All Categories', categories_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Myblog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">My Blog</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor03" aria-controls="navbarColor03" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor03">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <a class="nav-link" href="<%= root_path%>">Home <span class="sr-only">(current)</span></a>
        
      </li>
      <li class="nav-item">
         <a class="nav-link" href="<%= about_path%>">About</a>
      </li>
      <li class="nav-item">
         <a class="nav-link" href="<%= posts_path%>">Blog</a>
      </li>
      <li class="nav-item">
         <a class="nav-link" href="<%= contact_path%>">Contact</a>
      </li>
      <li class="nav-item">
         <a class="nav-link" href="<%= resources_path%>">Resources</a>
      </li>
    </ul>
    <form class="form-inline my-2 my-lg-0">  
      <input class="form-control mr-sm-2" type="text" placeholder="Search">
      <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

  <div class="container" style="margin-top: 25px;">

    <%= yield %>

  </div>

  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/resources.html.erb
<h1>Pages#resources</h1>
<p>Find me in app/views/pages/resources.html.erb</p>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %> <br/>
		<%= f.text_field :title %> <br/>
	</p>

	<p>
		<%= f.label :body %> <br/>
		<%= f.text_area :body %> <br/>
	</p>

	<p>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %> <br/>
	</p>

	<p>
		<%= f.submit "Update Post" %> <br/>
	</p>

<% end %>

<%= link_to "Go back", post_path  %>

app/views/posts/index.html.erb
<!-- <h1>Blog posts</h1> -->
<div class="row">
	<div class="col-md-8">
		<% @posts.each do |post| %>
		<div class="jumbotron" style="margin-bottom: 10px;">
			<h3><%= link_to post.title, post%></h3>
			<span class="badge badge-pill badge-secondary"><%=  post.category.name%></span>
			<br><br>
			<p class="lead"><%= post.body%></p>
		</div>
	<% end %>

	</div>

	<div class="col-md-4">
		<h4>Categories</h4>
		<div class="list-group">
			<% @categories.each do |category| %>
				 <a href="<%= category_path(:id => category.id) %>" class="list-group-item list-group-item-action">
		    <%= category.name %>
		  </a>

			<% end %>


		 <!--  <a href="#" class="list-group-item list-group-item-action active">
		    Cras justo odio
		  </a>
		  <a href="#" class="list-group-item list-group-item-action">Dapibus ac facilisis in
		  </a>
		  <a href="#" class="list-group-item list-group-item-action">Morbi leo risus
		  </a> -->

		</div>
	</div>
</div>

app/views/posts/new.html.erb
<h1>Add New Post</h1>
<%= form_for @post do |f| %>
	<p>
		<%= f.label :title %> <br/>
		<%= f.text_field :title %> <br/>
	</p>

	<p>
		<%= f.label :body %> <br/>
		<%= f.text_area :body %> <br/>
	</p>

	<p>
		<%= f.select :category_id, Category.all.collect {|x| [x.name, x.id]}, {:include_blank => "Select One"} %> <br/>
	</p>

	<p>
		<%= f.submit "Add Post" %> <br/>
	</p>

<% end %>

app/views/posts/show.html.erb
<h1> <%= @post.title%> </h1>
<p><%= @post.created_at.strftime("%b %d. %Y") %></p>

<p><%= @post.body %></p>
<br>
<p><strong>Category: </strong> <%= link_to @post.category.name, category_path(:id => @post.category.id) %></p>

<hr>
<%= link_to "All Posts", posts_path %>